// @generated by tools/cvgen from content/. DO NOT EDIT BY HAND.
// Regenerate with: cargo run --manifest-path tools/cvgen/Cargo.toml
// Compile with:    typst compile cv.typ
#set document(title: "John Scarrott — Curriculum Vitae", author: "John Scarrott")
#set page(paper: "a4", margin: (left: 1.4cm, right: 1.4cm, top: 1.2cm, bottom: 1.6cm))
#set text(font: "Liberation Sans", size: 9.5pt, fill: rgb("#333333"))
#set par(justify: true, leading: 0.62em)

#let accent = rgb("#27ae60")
#let muted = rgb("#5d5d5d")

#let section(title) = {
  v(8pt)
  text(size: 13pt, weight: "bold", fill: accent, smallcaps(title))
  v(1pt)
  line(length: 100%, stroke: 0.6pt + accent)
  v(3pt)
}

#let skill(name, items) = {
  grid(columns: (33%, 1fr), gutter: 10pt, text(weight: "bold", hyphenate: false, name), text(items))
  v(2pt)
}

#let item(lead, rest) = {
  if lead == "" { text(fill: muted, rest) } else { text(fill: muted, strong(lead) + " " + rest) }
}

#let entry(title, org, location, date, body) = {
  block(below: 8pt, breakable: false, {
    grid(columns: (1fr, auto), text(weight: "bold", title) + text(", " + org), text(fill: muted, date))
    text(fill: muted, style: "italic", size: 9pt, location)
    body
  })
}

#align(center)[
  #text(size: 26pt)[John #text(fill: accent, weight: "bold")[Scarrott]]
  #linebreak()
  #v(2pt)
  #text(size: 11pt, fill: muted, "Software Engineer · Problem Solver")
  #v(3pt)
  #text(size: 8.5pt, "john@scarrotts.uk  |  (+44) 7733298950  |  www.jscarrott.com  |  github.com/jscarrott  |  Barnstaple, Devon, UK")
]
#v(6pt)

#section("Skills")
#skill("Systems Programming Languages", "Rust, C++, C")
#skill("Managed Programming Languages", "Python, C#, F#, Java, Powershell")
#skill("Programming Paradigms", "Test Driven Development, Behavior Driven Development, Extreme programming")
#skill("Database Technologies", "SQL, Redis, QuestDb, SQL Server, Postgres")
#skill("Containerisation", "Docker, Podman, Kubernetes, GKE, AKS")
#skill("Infrastructure Technologies", "Terraform, Datadog, Jaeger")
#skill("CI/CD", "Github Actions, FluxCD, ArgoCD, PlzRelease")
#skill("Testing Technologies", "Pytest, NUnit, GoogleTest, GoogleMock, MSTest, Isolate")
#skill("Project Organisation Tools", "Github Issues, JIRA, Confluence, Agile, RCSPro, SCRUM")

#section("Experience")
#entry("Senior Rust Software Engineer", "Razorsecure", "Remote", "December 2019 - PRESENT", list(
  item("Platform lead:", "Responsible for the technical direction for one of the product platforms. In charge of the technical roadmap and leadership around the platform"),
  item("Development of deep package inspection library:", "Developed using zero-copy rust code and with eBPF (XDP) support, capable of sub-micro second latency and 1mpps+. Used as the basis for a next generation intrusion detection product"),
  item("Deployment of air-gapped kubernetes cluster:", "Bundling and supporting a on-premise kubernetes cluster alongside a cloud hosted version"),
  item("Development of high performance firewall for embedded security gateway:", "Development of a L2 to L7 firewall to protect critical network Infrastructure running a single protocol"),
  item("Migration of a python based client to Rust:", "Lead developer in the migration of a legacy python client to a high performance Rust version for the company's flagship product"),
  item("Development and management of python microservice using terraform and kubernetes:", "Use of monorepo build tool pants to orchestrate maintaining 20+ microservices"),
  item("Contribution to open source libraries:", "Small contributions to rust libraries for L2 Network monitoring and Flamegraphs"),
))

#entry("Software Engineer", "Helitune/Beran Instruments", "Torrington, North Devon", "Jun. 2015 - December 2019", list(
  item("Development of Next Generation Protection and Condition Monitoring systems:", "Development and systems engineering of a next generation system for large plant monitoring. Championed the use of Rust for several of the system modules. Running a dockerised signal processing and logging system on a embedded target. Currently deploying to the NASA Ames research center."),
  item("Development of Best in Class Rotor Track and Balance Systems:", "Development and maintenance of class leading RTB system, both carry on and permanent fit. Written to DO-178 level C and D standard."),
  item("Implementation of an all new C++ module based signal processing system:", "Allowing for the transition of all existing and new products to the new platform. The easily testable and replaceable system shortened development time and lead to a more robust system. It also synergised with the agile manifesto allowing for individual user stories to be tested more easily."),
  item("Extensive knowledge of C#/WPF:", "Developed and maintained several large (100,000+ line) projects, involved in all parts of the software lifecycle, from writing new software to maintaining legacy systems. Experience with both TDD and BDD design."),
  item("Debugging in low level environments:", "Debugging issues when the standard tools are unavailable is one of the more interesting challenges in software engineering. The ability to debug in these difficult situations is important as it enables the company to move forward without the purchase of expensive tooling and subsequent delays."),
  item("Development of a C#/WPF automated testing software for new product line:", "The fully automated testing of the product saved hundreds of man hours, catching production faults that would otherwise have gone unnoticed. Its configuration based design allowed it be the basis of several other products with minimal development effort."),
  item("Version Control Systems:", "As part of the company's transition to the Git version control system from TFS, I gained valuable experience in teaching people how to use a DVCS. Explaining and justifying the decisions behind the various strategies used to manage source gave me a thorough grounding in how they are best used. This has enabled the company to have multiple developers collaborate on a project with ease, and for the first time incorporate code review into the daily development workflow."),
  item("Continuous Integration:", "A successful CI workflow requires the orchestration of several different technologies. From the generation of VMs using tools such as packer/vagrant, the hosting of those VMs using vSphere and the management of build agents using teamcity. I have personally managed each of these processes and been involved in continuous improvement programs to streamline them."),
  item("Multi-Discipline Teamwork:", "Working as part of a cross-skilled team requires strong communication in order to achieve a successful result. On several occasions I have been required to liaise with engineers from different disciplines to fix critical issues under time pressure. My ability to remain level headed and ensure information was shared clearly helped to ship product on time."),
))

#section("Extracurricular Activity")
#entry("Author", "Md-book combiner", "Github", "2023-", list(
  item("", "Simple high-value tool for combining mdbooks from multiple repositories into one"),
  item("", "Leveraged automated releases to make deployment simple"),
  item("", "High complexity to value ratio for personal usecase"),
))

#entry("Contributor", "Rust nRF52 Hal", "Github", "2018-", list(
  item("", "Experienced developing at the cutting edge, implementing Rust only hardware abstraction on a micro-controller."),
  item("", "Being the first to run Rust on the nRF52840 chip proved a real problem solving challenge."),
))

#entry("Author", "Shell Config Manager", "Github", "2018-", list(
  item("", "Simple set of scripts for managing shell configuration files across machines and platforms, supporting powershell and Zsh."),
  item("", "Leveraging my experience with DVCS to solve another engineering problem."),
  item("", "Available as a powershell package as PshConfigMan."),
))

#section("Education")
#entry("BSc. in Computing and Psychology", "The Open University", "England", "2011 - 2015", list(
  item("", "Software development and the psychology behind user interface design"),
))

#entry("C for Real-Time Developers", "Feabhas", "Royal Wooten Basset", "2016", list(
  item("", "Intensive five day course on writing low-level C with and without a real time operating system."),
))

#entry("Advanced C++ Development", "Feabhas", "Royal Wooten Basset", "2016", list(
  item("", "Intensive five day course on writing C++ on micro-controllers."),
  item("", "Learned many of the pitfalls with the C++ language."),
  item("", "Learned how to leverage the more technical features of the language."),
))

