// @generated by tools/cvgen from content/. DO NOT EDIT BY HAND.
// Regenerate with: cargo run --manifest-path tools/cvgen/Cargo.toml

#![allow(dead_code)]

pub struct Profile {
    pub name: &'static str,
    pub position: &'static str,
    pub email: &'static str,
    pub phone: &'static str,
    pub homepage: &'static str,
    pub github: &'static str,
    pub location: &'static str,
}

pub struct Bullet {
    pub lead: &'static str,
    pub rest: &'static str,
}

pub struct Entry {
    pub slug: &'static str,
    pub title: &'static str,
    pub org: &'static str,
    pub location: &'static str,
    pub date: &'static str,
    pub emoji: &'static str,
    pub accent: &'static str,
    pub bullets: &'static [Bullet],
}

pub struct SkillCategory {
    pub name: &'static str,
    pub items: &'static str,
}

pub const PROFILE: Profile = Profile {
    name: "John Scarrott",
    position: "Platform Lead • Rust & Systems Engineer",
    email: "john@scarrotts.uk",
    phone: "(+44) 7733298950",
    homepage: "www.jscarrott.com",
    github: "github.com/jscarrott",
    location: "Barnstaple, Devon, UK",
};

pub const ABOUT: &[&str] = &[
    "I'm a software engineer and platform lead at RazorSecure, where we build intrusion",
    "detection for the rail industry — on-train agents reporting back to a wayside and",
    "cloud platform. I set the technical direction across our platforms and am currently",
    "leading the migration of our on-train detection agent from Python to Rust, alongside",
    "building the internal tooling our engineers and testers rely on day to day.",
    "",
    "I've been building software professionally for over a decade. I started out in",
    "safety-critical embedded systems — helicopter health monitoring written to DO-178 —",
    "before moving into high-performance networking, security and cloud-native",
    "infrastructure. These days I work mostly in Rust and Python, and I'm at my best on",
    "low-level, performance-sensitive problems and the tooling and systems around them.",
    "",
    "What I tend to focus on:",
    "• High-performance, zero-copy network programming in Rust",
    "• Cloud-native platform and release engineering (Kubernetes, Helm, Terraform)",
    "• Technical leadership and cross-platform architecture",
    "• Pragmatic migrations — modernising real systems without big-bang rewrites",
    "• Developer and test tooling — from terminal UIs to full-stack internal platforms",
    "",
    "Outside work I build things for fun — at the moment a physics simulator for testing",
    "an autonomous sailboat — and contribute to open source.",
];

pub const SKILLS: &[SkillCategory] = &[
    SkillCategory { name: "Systems Programming", items: "Rust (Tokio async, FFI elimination, multi-call binaries, eBPF/XDP), C++, C" },
    SkillCategory { name: "Rust Applications & UI", items: "Loco, GPUI desktop apps, ratatui TUIs, WebAssembly (ratzilla)" },
    SkillCategory { name: "Backend & APIs", items: "Python (FastAPI, Pydantic v2, Celery, uv), MCP servers, OAuth 2.0/PKCE & SSO" },
    SkillCategory { name: "Frontend", items: "TypeScript, React (Mantine, TanStack Query, React Router), Vite, Playwright" },
    SkillCategory { name: "Databases", items: "PostgreSQL (advanced indexing & partition tuning), MySQL, SQLite, QuestDB, Elasticsearch, Redis, RabbitMQ" },
    SkillCategory { name: "Containerisation & Orchestration", items: "Docker, Podman, Kubernetes, Helm, GKE, AKS, Talos Linux, Rook-Ceph, MetalLB" },
    SkillCategory { name: "Infrastructure & Release Engineering", items: "Terraform/Terragrunt, Skaffold, Pants, Replicated, Harbor, GitHub Actions, ArgoCD, FluxCD, SOPS, bors-ng merge queues, SonarCloud" },
    SkillCategory { name: "Observability", items: "Grafana, Datadog APM, statsd" },
    SkillCategory { name: "Domain & Protocols", items: "Rail network protocols, ELR/miles-and-chains, DPI/Suricata, SNMP, MQTT, ARP, GPS/NMEA/gpsd" },
    SkillCategory { name: "Engineering Practice", items: "Strangler-fig migration, TDD & BDD (Pytest, cargo test), Conventional Commits & release automation, ADRs, C4/D2 architecture modelling, secure-by-design" },
    SkillCategory { name: "Leadership", items: "Cross-platform roadmapping, technical-direction setting, migration & rollback planning, effort estimation" },
    SkillCategory { name: "Project Organisation", items: "GitHub Issues & Epics, JIRA, Confluence, Agile/SCRUM" },
    SkillCategory { name: "Previously (not current)", items: "C#/WPF, F#, Java, PowerShell, SQL Server, NUnit, GoogleTest/GoogleMock, TeamCity, vSphere, packer/vagrant" },
];

pub const EXPERIENCE: &[Entry] = &[
    Entry {
        slug: "razorsecure",
        title: "Senior Rust Software Engineer & Platform Lead",
        org: "RazorSecure",
        location: "Remote",
        date: "December 2019 - Present",
        emoji: "🚀",
        accent: "yellow",
        bullets: &[
            Bullet { lead: "Platform technical lead:", rest: "Set the technical direction for the product and author cross-platform roadmaps coordinating the on-train Agent, Frontend and Microservices/Backend platforms, so an architectural decision on one doesn't break another. Work is tracked as GitHub epics through an idea → buy-in → ticketed → planned → done lifecycle, and includes a push-based configuration-management design, a staged roadmap for offline (air-gapped) agent deployment, and an RBAC migration plan." },
            Bullet { lead: "Rust rewrite of the on-train detection agent (Python → Rust):", rest: "Driving an incremental \"strangler-fig\" migration that ships one stage per sprint with no big-bang cutover. Built the agent as a multi-call single binary (clap) on a Tokio runtime, with structured async task supervision, `panic=unwind` so a faulty monitor restarts rather than aborting the process, a lifecycle state machine, and self-monitoring with health heartbeats. Reimplemented the full monitor suite to strict parity with the Python agent (network DoS / port-scan / ARP, USB, syslog via journald, Suricata DPI, SNMP, GPS via gpsd, file/inotify, nftables and more) and drove the codebase toward pure-Rust dependencies, dropping C-FFI libraries such as libsnmp and paho-mqtt. Hardened the codebase with a parse-don't-validate pass (newtypes and enums for PSKs, endpoints, protocol versions and rail-protocol fields) and a cargo-nextest test workflow." },
            Bullet { lead: "Rail-network monitoring:", rest: "Productionised monitoring of on-train network protocols in the Rust agent, carrying it end to end through the platform: configuration in the dashboard, typed config delivered to devices, and an operator guide." },
            Bullet { lead: "High-performance detection core:", rest: "Designed and built a zero-copy Rust deep packet inspection library with eBPF (XDP) acceleration, sustaining sub-microsecond latency and 1 million+ packets per second as the basis of the intrusion-detection product, plus an L2-to-L7 firewall for an embedded security gateway protecting critical rail network infrastructure." },
            Bullet { lead: "Cloud portability and on-prem deployment:", rest: "Migrated storage and business logic off Google Cloud onto S3-compatible storage and made the entire platform deployable on-prem and on Azure — in-cluster Elasticsearch, Terraform fixes, and removal of cloud-provider-only assumptions across every Helm chart — including air-gapped Kubernetes clusters running alongside the cloud-hosted offering. Built an on-prem test rack on Talos Linux Kubernetes managed entirely by Flux GitOps (Rook-Ceph storage, MetalLB, SOPS-encrypted secrets and a Harbor pull-through registry mirror)." },
            Bullet { lead: "Deployment and release engineering:", rest: "Consolidated dozens of per-microservice Helm deployments into a single platform Helm chart (bringing Redis, QuestDB and RabbitMQ into the chart), moved CI off developer machines into GitHub Actions, and introduced a Harbor OCI registry with Replicated-based on-prem distribution. Built release automation around git-cliff changelogs, Conventional-Commit linting, release actions and grouped Dependabot updates. Later moved every Python service to PEP 621 packaging resolved with uv and a shared run-service entrypoint, derived image and chart versions from git describe via Pants, ran database migrations once per release instead of per replica, and extended our bors-ng merge queue to land a whole GitHub native PR stack from a single `r+`." },
            Bullet { lead: "Data-store performance and platform uplift:", rest: "Led deep PostgreSQL alert-store performance work — functional indexes on JSON fields, tsvector search predicates, partition pruning, bulk multi-row inserts and Celery tuning to eliminate out-of-memory failures during large batch jobs — alongside a MySQL 8.4 migration, a Pydantic v2 / FastAPI uplift across services, RabbitMQ 4.2 clustering, QuestDB ingest and memory-leak fixes, and an Elasticsearch migration to a Helm-hosted, tiered deployment with reindex-from-remote." },
            Bullet { lead: "Rail-specific detection and domain features:", rest: "Implemented rail geospatial logic (lat/long → ELR plus miles-and-chains) and a range of new monitors and protocol support — Suricata DPI, an SSH honeypot, several rail-network protocols, mirrored-traffic and VLAN-strip handling, rate-limiting and time-based event prioritisation — plus a new customer-configuration microservice." },
            Bullet { lead: "Observability:", rest: "Built a Grafana proxy architecture with authenticated endpoints and config-map-preloaded dashboards, later tuned with per-data-class cache TTLs, request coalescing and compressed large-panel responses, and instrumented the platform throughout with Datadog APM tracing and statsd metrics." },
            Bullet { lead: "Test-evidence platform:", rest: "Designed and built, from scratch, the company's platform for manual test execution and evidence capture. It is a Rust (Loco) JSON API with a React and TypeScript SPA (Mantine, TanStack Query), deployed to Kubernetes through GitOps. Features include a versioned test library with shared steps, published test plans stored as immutable snapshots with drift diffs, step-by-step runs with pasted or dragged-in evidence, and requirements traceability with version history and roll-up coverage. It also has role-based sign-off with a review queue, SSO, and OAuth with PKCE. An MCP server lets AI agents author tests and record results, and each run exports as a Typst PDF report." },
            Bullet { lead: "Engineering tooling:", rest: "Built a native Rust desktop configurator (GPUI) that authors the agent, processor and monitor-plan configuration, replacing a single-file web tool. It keeps versioned drafts for each system, copies configuration between near-identical train variants by matching lineage, and ships a Windows build. Also wrote ratatui terminal tools that generate realistic test traffic: train-network data, and NMEA GPS tracks along real rail routes using OpenStreetMap data, A* routing and a train motion model." },
            Bullet { lead: "Test and documentation discipline:", rest: "Built a multi-tier BDD test harness spanning the agent, processing and integration layers up to end-to-end tests driven through a real MQTT broker, with a JUnit aggregator that produces a Typst PDF test report and parallel Docker-based BDD in CI; established documentation conventions (and moved the company docs site from mdBook to VitePress) with topical docs and Mermaid / C4 / D2 architecture diagrams, and contributed to open-source Rust libraries for layer-2 network monitoring and flame-graph performance analysis." },
        ],
    },
    Entry {
        slug: "helitune",
        title: "Software Engineer",
        org: "Helitune/Beran Instruments",
        location: "Torrington, North Devon",
        date: "June 2015 - December 2019",
        emoji: "⚙️",
        accent: "green",
        bullets: &[
            Bullet { lead: "Next-generation protection and condition monitoring:", rest: "Development and systems engineering of a next-generation system for large-plant monitoring. Championed the use of Rust for several of the system modules, running a dockerised signal-processing and logging system on an embedded target — being deployed at the NASA Ames Research Center." },
            Bullet { lead: "Rotor Track and Balance systems:", rest: "Developed and maintained a best-in-class RTB system in both carry-on and permanent-fit configurations, written to DO-178 Level C and D." },
            Bullet { lead: "Modular C++ signal-processing system:", rest: "Designed an all-new, module-based C++ signal-processing system that let existing and new products move onto a single platform. Being easily testable and replaceable, it shortened development time, made the system more robust, and fit well with agile working." },
            Bullet { lead: "C#/WPF applications:", rest: "Developed and maintained several large (100,000+ line) C#/WPF projects across the whole software lifecycle, and built a configuration-driven automated test application that saved hundreds of hours and caught production faults before release." },
            Bullet { lead: "Version control and CI:", rest: "Led the company's move from TFS to Git — teaching teams distributed version control and introducing code review — and built the CI workflow around it with packer/vagrant, vSphere and TeamCity." },
        ],
    },
];

pub const EDUCATION: &[Entry] = &[
    Entry {
        slug: "open-university",
        title: "BSc. in Computing and Psychology",
        org: "The Open University",
        location: "England",
        date: "2011 - 2015",
        emoji: "🎓",
        accent: "yellow",
        bullets: &[
            Bullet { lead: "", rest: "Software development and the psychology behind user interface design" },
        ],
    },
    Entry {
        slug: "c-realtime",
        title: "C for Real-Time Developers",
        org: "Feabhas",
        location: "Royal Wootton Bassett",
        date: "2016",
        emoji: "⚡",
        accent: "green",
        bullets: &[
            Bullet { lead: "", rest: "Intensive five day course on writing low-level C with and without a real time operating system." },
        ],
    },
    Entry {
        slug: "advanced-cpp",
        title: "Advanced C++ Development",
        org: "Feabhas",
        location: "Royal Wootton Bassett",
        date: "2016",
        emoji: "🔧",
        accent: "blue",
        bullets: &[
            Bullet { lead: "", rest: "Five-day course on C++ for micro-controllers: its pitfalls and advanced features." },
        ],
    },
];

pub const PROJECTS: &[Entry] = &[
    Entry {
        slug: "sailboat-simulator",
        title: "Author",
        org: "STDA Sailboat Simulator",
        location: "GitHub",
        date: "2023-",
        emoji: "⛵",
        accent: "orange",
        bullets: &[
            Bullet { lead: "", rest: "Building a physics-based simulator to design, develop and test an autonomous sailboat before deploying to real hardware." },
            Bullet { lead: "", rest: "Ported the 6-degree-of-freedom (6-DOF) dynamics core to Rust from a published autonomous-sailing model (Sailing Team Darmstadt, IRSC 2018), and extended it with route-following, real nautical-chart navigation and a speed-polar calibration instrument." },
            Bullet { lead: "", rest: "Rust and Python, working toward calibrating the model against real-world data for a hardware retrofit and autonomous-control trials." },
        ],
    },
    Entry {
        slug: "homebox-addon",
        title: "Author",
        org: "Homebox Home Assistant Add-on",
        location: "GitHub",
        date: "2025-",
        emoji: "🏠",
        accent: "purple",
        bullets: &[
            Bullet { lead: "", rest: "Home Assistant add-on that packages Homebox (a self-hosted home inventory tool) for one-click installation through the Home Assistant Supervisor." },
            Bullet { lead: "", rest: "My most-starred public project, used by the wider Home Assistant community." },
            Bullet { lead: "", rest: "Maintained add-on repository with a containerised build and release flow." },
        ],
    },
    Entry {
        slug: "mdbook-combiner",
        title: "Author",
        org: "Md-book combiner",
        location: "Github",
        date: "2023-",
        emoji: "📖",
        accent: "yellow",
        bullets: &[
            Bullet { lead: "", rest: "Small tool that combines mdBooks from multiple repositories into one site, shipped through automated releases." },
        ],
    },
    Entry {
        slug: "jjui-plugin-manager",
        title: "Author",
        org: "jjui-pm",
        location: "GitHub",
        date: "2026-",
        emoji: "🔌",
        accent: "teal",
        bullets: &[
            Bullet { lead: "", rest: "CLI plugin manager, written in Rust, for jjui — a TUI for the Jujutsu (jj) version-control system." },
            Bullet { lead: "", rest: "Manages Lua plugins by reading and modifying the jjui config file; installable via cargo." },
            Bullet { lead: "", rest: "Reflects deep day-to-day use of Jujutsu and the Rust terminal-UI ecosystem." },
        ],
    },
    Entry {
        slug: "nrf52-hal",
        title: "Contributor",
        org: "Rust nRF52 Hal",
        location: "Github",
        date: "2018-",
        emoji: "🔧",
        accent: "green",
        bullets: &[
            Bullet { lead: "", rest: "Experienced developing at the cutting edge, implementing Rust only hardware abstraction on a micro-controller." },
            Bullet { lead: "", rest: "Being the first to run Rust on the nRF52840 chip proved a real problem solving challenge." },
        ],
    },
];

